name: Test Connection for Pipeline

on:
  workflow_call:
    

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name : Echo Message
        run: echo "Github Action working successfully ✅"